# Generated by Django 3.2.12 on 2022-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_alter_prettynum_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
